In [1]:
#Data Understanding und Data Preparation - 1: EinfÃ¼hrung | VidalDosSantos, Jelic, Forte
#The File contains information about how long the execution of a cell takes (format HH:MM:SS). duration for this file aprox. 00:03:02.

In [2]:
#imports used in this file
import numpy as np
import pandas as pd

In [3]:
#Dataset downloaded from Kaggle: https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents
#read-in data as pandaFrame
df_accidents = pd.read_csv('data/edited_file.csv', index_col = 'ID')
#convert to numpy-Array in order to execute ops and print np_accidents 
np_accidents = df_accidents.to_numpy()
np_accidents
#aprox. 00:00:50

array([[2, '2016-02-08 06:49:27', '2016-02-08 07:19:27', ..., 'Night',
        'Day', 'Day'],
       [3, '2016-02-08 07:23:34', '2016-02-08 07:53:34', ..., 'Day',
        'Day', 'Day'],
       [2, '2016-02-08 07:39:07', '2016-02-08 08:09:07', ..., 'Day',
        'Day', 'Day'],
       ...,
       [2, '2019-08-23 19:00:21', '2019-08-23 19:28:49', ..., 'Day',
        'Day', 'Day'],
       [2, '2019-08-23 19:00:21', '2019-08-23 19:29:42', ..., 'Day',
        'Day', 'Day'],
       [2, '2019-08-23 18:52:06', '2019-08-23 19:21:31', ..., 'Day',
        'Day', 'Day']], dtype=object)

In [4]:
#In Order to check which Features are eligible for filtering we would like to have an overview over the datatypes
print(df_accidents.dtypes)

Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
Distance(mi)             float64
Description               object
Street                    object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Temperature(F)           float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [6]:
#filter data with 2 conditions
#filter the the Feature Severity. Take every entry bigger than 2
#filter for temperature for values >20F and <50F
#get right columns
severity_feature = np_accidents[:,0]
temperature_feature = np_accidents[:,18]

#filter and print
print(np_accidents[np.argwhere(severity_feature > 2)])
print('-----------------------------------------------------------------')
print(np_accidents[np.argwhere((temperature_feature > 20) & (temperature_feature < 50))])
#--> after executing this cell we can see in the error printed that temperature contains invalid values --> data cleaning --> still outputs...

[[[3 '2016-02-08 07:23:34' '2016-02-08 07:53:34' ... 'Day' 'Day' 'Day']]

 [[3 '2016-02-08 07:44:26' '2016-02-08 08:14:26' ... 'Day' 'Day' 'Day']]

 [[3 '2016-02-08 07:59:58' '2016-02-08 08:29:58' ... 'Day' 'Day' 'Day']]

 ...

 [[4 '2019-08-23 13:39:48' '2019-08-23 14:05:33' ... 'Day' 'Day' 'Day']]

 [[4 '2019-08-23 13:39:48' '2019-08-23 14:05:33' ... 'Day' 'Day' 'Day']]

 [[4 '2019-08-23 16:51:29' '2019-08-23 17:21:02' ... 'Day' 'Day' 'Day']]]
-----------------------------------------------------------------
[[[2 '2016-06-21 12:33:43' '2016-06-21 13:03:43' ... 'Day' 'Day' 'Day']]

 [[2 '2016-06-21 13:34:39' '2016-06-21 14:04:39' ... 'Day' 'Day' 'Day']]

 [[3 '2016-06-21 16:02:09' '2016-06-21 16:32:09' ... 'Day' 'Day' 'Day']]

 ...

 [[2 '2019-08-22 14:15:37' '2019-08-22 14:45:31' ... 'Day' 'Day' 'Day']]

 [[2 '2019-08-22 14:15:37' '2019-08-22 14:45:31' ... 'Day' 'Day' 'Day']]

 [[4 '2019-08-23 09:01:45' '2019-08-23 09:29:31' ... 'Day' 'Day' 'Day']]]

In [7]:
#statistics mean_severity and median temperature
print('the mean severity is: ' + str(np.mean(severity_feature)))
print(str(np.median(temperature_feature)) + '(F)')

the mean severity is: 2.202577984206606
10.0(F)

In [10]:
#calculate new column --> since we didnt found a good combination we are going to combine severity and the description (int + object)
df_accidents['severity_description'] = df_accidents['Severity'].astype(str) + ': ' + df_accidents['Description'].astype(str)
print(df_accidents['severity_description'])

ID
A-3          2: Accident on OH-32 State Route 32 Westbound ...
A-4          3: Accident on I-75 Southbound at Exits 52 52B...
A-5          2: Accident on McEwen Rd at OH-725 Miamisburg ...
A-6          3: Accident on I-270 Outerbelt Northbound near...
A-7          2: Accident on Oakridge Dr at Woodward Ave. Ex...
                                   ...
A-7777757                          2: At Market St - Accident.
A-7777758    2: At Camino Del Rio/Mission Center Rd - Accid...
A-7777759    2: At Glassell St/Grand Ave - Accident. in the...
A-7777760    2: At CA-90/Marina Fwy/Jefferson Blvd - Accident.
A-7777761             2: At Highland Ave/Arden Ave - Accident.
Name: severity_description, Length: 7051556, dtype: object

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,City,County,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,severity_description
ID,,,,,,,,,,,,,,,,,,,,,
A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.010,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,...,False,False,False,True,False,Night,Night,Day,Day,2: Accident on OH-32 State Route 32 Westbound ...
A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.010,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,...,False,False,False,False,False,Night,Day,Day,Day,3: Accident on I-75 Southbound at Exits 52 52B...
A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,...,False,False,False,True,False,Day,Day,Day,Day,2: Accident on McEwen Rd at OH-725 Miamisburg ...
A-6,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,0.010,Accident on I-270 Outerbelt Northbound near Ex...,Westerville Rd,Westerville,Franklin,...,False,False,False,False,False,Day,Day,Day,Day,3: Accident on I-270 Outerbelt Northbound near...
A-7,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,0.000,Accident on Oakridge Dr at Woodward Ave. Expec...,N Woodward Ave,Dayton,Montgomery,...,False,False,False,False,False,Day,Day,Day,Day,2: Accident on Oakridge Dr at Woodward Ave. Ex...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A-7777757,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,0.543,At Market St - Accident.,Pomona Fwy E,Riverside,Riverside,...,False,False,False,False,False,Day,Day,Day,Day,2: At Market St - Accident.
A-7777758,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,0.338,At Camino Del Rio/Mission Center Rd - Accident.,I-8 W,San Diego,San Diego,...,False,False,False,False,False,Day,Day,Day,Day,2: At Camino Del Rio/Mission Center Rd - Accid...
A-7777759,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,0.561,At Glassell St/Grand Ave - Accident. in the ri...,Garden Grove Fwy,Orange,Orange,...,False,False,False,False,False,Day,Day,Day,Day,2: At Glassell St/Grand Ave - Accident. in the...
A-7777760,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,San Diego Fwy S,Culver City,Los Angeles,...,False,False,False,False,False,Day,Day,Day,Day,2: At CA-90/Marina Fwy/Jefferson Blvd - Accident.
A-7777761,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,0.537,At Highland Ave/Arden Ave - Accident.,CA-210 W,Highland,San Bernardino,...,False,False,False,False,False,Day,Day,Day,Day,2: At Highland Ave/Arden Ave - Accident.

In [15]:
#change naming
df_accidents.rename(columns={'severity_description':'comb_sev_desc'}, inplace=True)

In [13]:
#change order of columns
cols = list(df_accidents.columns)
cols[-2], cols[-1] = cols[-1], cols[-2]
df_accidents = df_accidents[cols]
print(df_accidents)

           Severity           Start_Time             End_Time  Start_Lat  \
ID
A-3               2  2016-02-08 06:49:27  2016-02-08 07:19:27  39.063148
A-4               3  2016-02-08 07:23:34  2016-02-08 07:53:34  39.747753
A-5               2  2016-02-08 07:39:07  2016-02-08 08:09:07  39.627781
A-6               3  2016-02-08 07:44:26  2016-02-08 08:14:26  40.100590
A-7               2  2016-02-08 07:59:35  2016-02-08 08:29:35  39.758274
...             ...                  ...                  ...        ...
A-7777757         2  2019-08-23 18:03:25  2019-08-23 18:32:01  34.002480
A-7777758         2  2019-08-23 19:11:30  2019-08-23 19:38:23  32.766960
A-7777759         2  2019-08-23 19:00:21  2019-08-23 19:28:49  33.775450
A-7777760         2  2019-08-23 19:00:21  2019-08-23 19:29:42  33.992460
A-7777761         2  2019-08-23 18:52:06  2019-08-23 19:21:31  34.133930

            Start_Lng  Distance(mi)  \
ID
A-3        -84.032608         0.010
A-4        -84.205582         0.010
A-5        -84.188354         0.010
A-6        -82.925194         0.010
A-7        -84.230507         0.000
...               ...           ...
A-7777757 -117.379360         0.543
A-7777758 -117.148060         0.338
A-7777759 -117.847790         0.561
A-7777760 -118.403020         0.772
A-7777761 -117.230920         0.537

                                                 Description  \
ID
A-3        Accident on OH-32 State Route 32 Westbound at ...
A-4        Accident on I-75 Southbound at Exits 52 52B US...
A-5        Accident on McEwen Rd at OH-725 Miamisburg Cen...
A-6        Accident on I-270 Outerbelt Northbound near Ex...
A-7        Accident on Oakridge Dr at Woodward Ave. Expec...
...                                                      ...
A-7777757                           At Market St - Accident.
A-7777758    At Camino Del Rio/Mission Center Rd - Accident.
A-7777759  At Glassell St/Grand Ave - Accident. in the ri...
A-7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.
A-7777761              At Highland Ave/Arden Ave - Accident.

                              Street          City          County  ...  \
ID                                                                  ...
A-3                   State Route 32  Williamsburg        Clermont  ...
A-4                           I-75 S        Dayton      Montgomery  ...
A-5        Miamisburg Centerville Rd        Dayton      Montgomery  ...
A-6                   Westerville Rd   Westerville        Franklin  ...
A-7                   N Woodward Ave        Dayton      Montgomery  ...
...                              ...           ...             ...  ...
A-7777757               Pomona Fwy E     Riverside       Riverside  ...
A-7777758                      I-8 W     San Diego       San Diego  ...
A-7777759           Garden Grove Fwy        Orange          Orange  ...
A-7777760            San Diego Fwy S   Culver City     Los Angeles  ...
A-7777761                   CA-210 W      Highland  San Bernardino  ...

          Station   Stop Traffic_Calming Traffic_Signal Turning_Loop  \
ID
A-3         False  False           False           True        False
A-4         False  False           False          False        False
A-5         False  False           False           True        False
A-6         False  False           False          False        False
A-7         False  False           False          False        False
...           ...    ...             ...            ...          ...
A-7777757   False  False           False          False        False
A-7777758   False  False           False          False        False
A-7777759   False  False           False          False        False
A-7777760   False  False           False          False        False
A-7777761   False  False           False          False        False

           Sunrise_Sunset  Civil_Twilight  Nautical_Twilight  \
ID
A-3                 Night           Night                Day
A-4                 Night             Day                Day
A-5                   Day             Day                Day
A-6                   Day             Day                Day
A-7                   Day             Day                Day
...                   ...             ...                ...
A-7777757             Day             Day                Day
A-7777758             Day             Day                Day
A-7777759             Day             Day                Day
A-7777760             Day             Day                Day
A-7777761             Day             Day                Day

                                        severity_description  \
ID
A-3        2: Accident on OH-32 State Route 32 Westbound ...
A-4        3: Accident on I-75 Southbound at Exits 52 52B...
A-5        2: Accident on McEwen Rd at OH-725 Miamisburg ...
A-6        3: Accident on I-270 Outerbelt Northbound near...
A-7        2: Accident on Oakridge Dr at Woodward Ave. Ex...
...                                                      ...
A-7777757                        2: At Market St - Accident.
A-7777758  2: At Camino Del Rio/Mission Center Rd - Accid...
A-7777759  2: At Glassell St/Grand Ave - Accident. in the...
A-7777760  2: At CA-90/Marina Fwy/Jefferson Blvd - Accident.
A-7777761           2: At Highland Ave/Arden Ave - Accident.

          Astronomical_Twilight
ID
A-3                         Day
A-4                         Day
A-5                         Day
A-6                         Day
A-7                         Day
...                         ...
A-7777757                   Day
A-7777758                   Day
A-7777759                   Day
A-7777760                   Day
A-7777761                   Day

[7051556 rows x 40 columns]

In [16]:
#delete column severity_source
df_accidents = df_accidents.drop('comb_sev_desc', axis=1)
print(df_accidents)

           Severity           Start_Time             End_Time  Start_Lat  \
ID
A-3               2  2016-02-08 06:49:27  2016-02-08 07:19:27  39.063148
A-4               3  2016-02-08 07:23:34  2016-02-08 07:53:34  39.747753
A-5               2  2016-02-08 07:39:07  2016-02-08 08:09:07  39.627781
A-6               3  2016-02-08 07:44:26  2016-02-08 08:14:26  40.100590
A-7               2  2016-02-08 07:59:35  2016-02-08 08:29:35  39.758274
...             ...                  ...                  ...        ...
A-7777757         2  2019-08-23 18:03:25  2019-08-23 18:32:01  34.002480
A-7777758         2  2019-08-23 19:11:30  2019-08-23 19:38:23  32.766960
A-7777759         2  2019-08-23 19:00:21  2019-08-23 19:28:49  33.775450
A-7777760         2  2019-08-23 19:00:21  2019-08-23 19:29:42  33.992460
A-7777761         2  2019-08-23 18:52:06  2019-08-23 19:21:31  34.133930

            Start_Lng  Distance(mi)  \
ID
A-3        -84.032608         0.010
A-4        -84.205582         0.010
A-5        -84.188354         0.010
A-6        -82.925194         0.010
A-7        -84.230507         0.000
...               ...           ...
A-7777757 -117.379360         0.543
A-7777758 -117.148060         0.338
A-7777759 -117.847790         0.561
A-7777760 -118.403020         0.772
A-7777761 -117.230920         0.537

                                                 Description  \
ID
A-3        Accident on OH-32 State Route 32 Westbound at ...
A-4        Accident on I-75 Southbound at Exits 52 52B US...
A-5        Accident on McEwen Rd at OH-725 Miamisburg Cen...
A-6        Accident on I-270 Outerbelt Northbound near Ex...
A-7        Accident on Oakridge Dr at Woodward Ave. Expec...
...                                                      ...
A-7777757                           At Market St - Accident.
A-7777758    At Camino Del Rio/Mission Center Rd - Accident.
A-7777759  At Glassell St/Grand Ave - Accident. in the ri...
A-7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.
A-7777761              At Highland Ave/Arden Ave - Accident.

                              Street          City          County  ...  \
ID                                                                  ...
A-3                   State Route 32  Williamsburg        Clermont  ...
A-4                           I-75 S        Dayton      Montgomery  ...
A-5        Miamisburg Centerville Rd        Dayton      Montgomery  ...
A-6                   Westerville Rd   Westerville        Franklin  ...
A-7                   N Woodward Ave        Dayton      Montgomery  ...
...                              ...           ...             ...  ...
A-7777757               Pomona Fwy E     Riverside       Riverside  ...
A-7777758                      I-8 W     San Diego       San Diego  ...
A-7777759           Garden Grove Fwy        Orange          Orange  ...
A-7777760            San Diego Fwy S   Culver City     Los Angeles  ...
A-7777761                   CA-210 W      Highland  San Bernardino  ...

          Roundabout Station   Stop Traffic_Calming Traffic_Signal  \
ID
A-3            False   False  False           False           True
A-4            False   False  False           False          False
A-5            False   False  False           False           True
A-6            False   False  False           False          False
A-7            False   False  False           False          False
...              ...     ...    ...             ...            ...
A-7777757      False   False  False           False          False
A-7777758      False   False  False           False          False
A-7777759      False   False  False           False          False
A-7777760      False   False  False           False          False
A-7777761      False   False  False           False          False

           Turning_Loop  Sunrise_Sunset  Civil_Twilight  Nautical_Twilight  \
ID
A-3               False           Night           Night                Day
A-4               False           Night             Day                Day
A-5               False             Day             Day                Day
A-6               False             Day             Day                Day
A-7               False             Day             Day                Day
...                 ...             ...             ...                ...
A-7777757         False             Day             Day                Day
A-7777758         False             Day             Day                Day
A-7777759         False             Day             Day                Day
A-7777760         False             Day             Day                Day
A-7777761         False             Day             Day                Day

          Astronomical_Twilight
ID
A-3                         Day
A-4                         Day
A-5                         Day
A-6                         Day
A-7                         Day
...                         ...
A-7777757                   Day
A-7777758                   Day
A-7777759                   Day
A-7777760                   Day
A-7777761                   Day

[7051556 rows x 39 columns]

In [17]:
#use str-Accesor --> replace ID (A-1 --> 1)
df_accidents.index = df_accidents.index.str.replace('A-','')
print(df_accidents)

         Severity           Start_Time             End_Time  Start_Lat  \
ID
3               2  2016-02-08 06:49:27  2016-02-08 07:19:27  39.063148
4               3  2016-02-08 07:23:34  2016-02-08 07:53:34  39.747753
5               2  2016-02-08 07:39:07  2016-02-08 08:09:07  39.627781
6               3  2016-02-08 07:44:26  2016-02-08 08:14:26  40.100590
7               2  2016-02-08 07:59:35  2016-02-08 08:29:35  39.758274
...           ...                  ...                  ...        ...
7777757         2  2019-08-23 18:03:25  2019-08-23 18:32:01  34.002480
7777758         2  2019-08-23 19:11:30  2019-08-23 19:38:23  32.766960
7777759         2  2019-08-23 19:00:21  2019-08-23 19:28:49  33.775450
7777760         2  2019-08-23 19:00:21  2019-08-23 19:29:42  33.992460
7777761         2  2019-08-23 18:52:06  2019-08-23 19:21:31  34.133930

          Start_Lng  Distance(mi)  \
ID
3        -84.032608         0.010
4        -84.205582         0.010
5        -84.188354         0.010
6        -82.925194         0.010
7        -84.230507         0.000
...             ...           ...
7777757 -117.379360         0.543
7777758 -117.148060         0.338
7777759 -117.847790         0.561
7777760 -118.403020         0.772
7777761 -117.230920         0.537

                                               Description  \
ID
3        Accident on OH-32 State Route 32 Westbound at ...
4        Accident on I-75 Southbound at Exits 52 52B US...
5        Accident on McEwen Rd at OH-725 Miamisburg Cen...
6        Accident on I-270 Outerbelt Northbound near Ex...
7        Accident on Oakridge Dr at Woodward Ave. Expec...
...                                                    ...
7777757                           At Market St - Accident.
7777758    At Camino Del Rio/Mission Center Rd - Accident.
7777759  At Glassell St/Grand Ave - Accident. in the ri...
7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.
7777761              At Highland Ave/Arden Ave - Accident.

                            Street          City          County  ...  \
ID                                                                ...
3                   State Route 32  Williamsburg        Clermont  ...
4                           I-75 S        Dayton      Montgomery  ...
5        Miamisburg Centerville Rd        Dayton      Montgomery  ...
6                   Westerville Rd   Westerville        Franklin  ...
7                   N Woodward Ave        Dayton      Montgomery  ...
...                            ...           ...             ...  ...
7777757               Pomona Fwy E     Riverside       Riverside  ...
7777758                      I-8 W     San Diego       San Diego  ...
7777759           Garden Grove Fwy        Orange          Orange  ...
7777760            San Diego Fwy S   Culver City     Los Angeles  ...
7777761                   CA-210 W      Highland  San Bernardino  ...

        Roundabout Station   Stop Traffic_Calming Traffic_Signal  \
ID
3            False   False  False           False           True
4            False   False  False           False          False
5            False   False  False           False           True
6            False   False  False           False          False
7            False   False  False           False          False
...            ...     ...    ...             ...            ...
7777757      False   False  False           False          False
7777758      False   False  False           False          False
7777759      False   False  False           False          False
7777760      False   False  False           False          False
7777761      False   False  False           False          False

         Turning_Loop  Sunrise_Sunset  Civil_Twilight  Nautical_Twilight  \
ID
3               False           Night           Night                Day
4               False           Night             Day                Day
5               False             Day             Day                Day
6               False             Day             Day                Day
7               False             Day             Day                Day
...               ...             ...             ...                ...
7777757         False             Day             Day                Day
7777758         False             Day             Day                Day
7777759         False             Day             Day                Day
7777760         False             Day             Day                Day
7777761         False             Day             Day                Day

        Astronomical_Twilight
ID
3                         Day
4                         Day
5                         Day
6                         Day
7                         Day
...                       ...
7777757                   Day
7777758                   Day
7777759                   Day
7777760                   Day
7777761                   Day

[7051556 rows x 39 columns]

In [18]:
df_accidents.to_csv('data/edited_file.csv')