In [1]:
#Data Understanding und Data Preparation - 1: EinfÃ¼hrung | VidalDosSantos, Jelic, Forte
#The File contains information about how long the execution of a cell takes (format HH:MM:SS). duration for this file aprox. 00:03:02.

In [2]:
#imports used in this file
import numpy as np
import pandas as pd

In [3]:
#Dataset downloaded from Kaggle: https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents
#read-in data as pandaFrame
df_accidents = pd.read_csv('data/US_Accidents_March23.csv', index_col = 'ID')
#convert to numpy-Array in order to execute ops and print np_accidents 
np_accidents = df_accidents.to_numpy()
np_accidents
#aprox. 00:00:50

array([['Source2', 3, '2016-02-08 05:46:00', ..., 'Night', 'Night',
        'Night'],
       ['Source2', 2, '2016-02-08 06:07:59', ..., 'Night', 'Night',
        'Day'],
       ['Source2', 2, '2016-02-08 06:49:27', ..., 'Night', 'Day', 'Day'],
       ...,
       ['Source1', 2, '2019-08-23 19:00:21', ..., 'Day', 'Day', 'Day'],
       ['Source1', 2, '2019-08-23 19:00:21', ..., 'Day', 'Day', 'Day'],
       ['Source1', 2, '2019-08-23 18:52:06', ..., 'Day', 'Day', 'Day']],
      dtype=object)

In [4]:
#In Order to check which Features are eligible for filtering we would like to have an overview over the datatypes
print(df_accidents.dtypes)

Source                    object
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Street                    object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [5]:
#filter data with 2 conditions
#filter the the Feature Severity. Take every entry bigger than 2
#filter for temperature for values >20F and <50F
#get right columns
severity_feature = np_accidents[:,1]
temperature_feature = np_accidents[:,19]

#filter and print
print(np_accidents[np.argwhere(severity_feature > 2)])
print('-----------------------------------------------------------------')
print(np_accidents[np.argwhere((temperature_feature > 20) & (temperature_feature < 50))])
#--> after executing this cell we can see in the error printed that temperature contains invalid values --> data cleaning --> still outputs...

[[['Source2' 3 '2016-02-08 05:46:00' ... 'Night' 'Night' 'Night']]

 [['Source2' 3 '2016-02-08 07:23:34' ... 'Day' 'Day' 'Day']]

 [['Source2' 3 '2016-02-08 07:44:26' ... 'Day' 'Day' 'Day']]

 ...

 [['Source1' 4 '2019-08-23 13:39:48' ... 'Day' 'Day' 'Day']]

 [['Source1' 4 '2019-08-23 13:39:48' ... 'Day' 'Day' 'Day']]

 [['Source1' 4 '2019-08-23 16:51:29' ... 'Day' 'Day' 'Day']]]
-----------------------------------------------------------------

C:\Users\forte\AppData\Local\Temp\ipykernel_11588\4106664054.py:11: RuntimeWarning: invalid value encountered in greater
  print(np_accidents[np.argwhere((temperature_feature > 20) & (temperature_feature < 50))])
C:\Users\forte\AppData\Local\Temp\ipykernel_11588\4106664054.py:11: RuntimeWarning: invalid value encountered in less
  print(np_accidents[np.argwhere((temperature_feature > 20) & (temperature_feature < 50))])

[[['Source2' 3 '2016-02-08 05:46:00' ... 'Night' 'Night' 'Night']]

 [['Source2' 2 '2016-02-08 06:07:59' ... 'Night' 'Night' 'Day']]

 [['Source2' 2 '2016-02-08 06:49:27' ... 'Night' 'Day' 'Day']]

 ...

 [['Source1' 3 '2019-08-22 05:52:08' ... 'Day' 'Day' 'Day']]

 [['Source1' 2 '2019-08-22 07:15:37' ... 'Day' 'Day' 'Day']]

 [['Source1' 2 '2019-08-23 04:29:01' ... 'Night' 'Night' 'Day']]]

In [6]:
#statistics mean_severity and median temperature
print('the mean severity is: ' + str(np.mean(severity_feature)))
print(str(np.median(temperature_feature)) + '(F)')

the mean severity is: 2.212384487643875
63.0(F)

In [7]:
#calculate new column
df_accidents['source_severity'] = df_accidents['Source'].astype(str) + df_accidents['Severity'].astype(str)
print(df_accidents['source_severity'])

ID
A-1          Source23
A-2          Source22
A-3          Source22
A-4          Source23
A-5          Source22
               ...
A-7777757    Source12
A-7777758    Source12
A-7777759    Source12
A-7777760    Source12
A-7777761    Source12
Name: source_severity, Length: 7728394, dtype: object

In [8]:
#change naming
df_accidents.rename(columns={'source_severity':'severity_source'})

,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,severity_source
ID,,,,,,,,,,,,,,,,,,,,,
A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,Right lane blocked due to accident on I-70 Eas...,...,False,False,False,False,False,Night,Night,Night,Night,Source23
A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,Accident on Brice Rd at Tussing Rd. Expect del...,...,False,False,False,False,False,Night,Night,Night,Day,Source22
A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,Accident on OH-32 State Route 32 Westbound at ...,...,False,False,False,True,False,Night,Night,Day,Day,Source22
A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,Accident on I-75 Southbound at Exits 52 52B US...,...,False,False,False,False,False,Night,Day,Day,Day,Source23
A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,...,False,False,False,True,False,Day,Day,Day,Day,Source22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A-7777757,Source1,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,0.543,At Market St - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,Source12
A-7777758,Source1,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,Source12
A-7777759,Source1,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,Day,Day,Day,Day,Source12
A-7777760,Source1,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,Source12
A-7777761,Source1,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,Source12

In [9]:
#change order of columns
cols = list(df_accidents.columns)
cols[-2], cols[-1] = cols[-1], cols[-2]
df_accidents = df_accidents[cols]
print(df_accidents)

            Source  Severity           Start_Time             End_Time  \
ID
A-1        Source2         3  2016-02-08 05:46:00  2016-02-08 11:00:00
A-2        Source2         2  2016-02-08 06:07:59  2016-02-08 06:37:59
A-3        Source2         2  2016-02-08 06:49:27  2016-02-08 07:19:27
A-4        Source2         3  2016-02-08 07:23:34  2016-02-08 07:53:34
A-5        Source2         2  2016-02-08 07:39:07  2016-02-08 08:09:07
...            ...       ...                  ...                  ...
A-7777757  Source1         2  2019-08-23 18:03:25  2019-08-23 18:32:01
A-7777758  Source1         2  2019-08-23 19:11:30  2019-08-23 19:38:23
A-7777759  Source1         2  2019-08-23 19:00:21  2019-08-23 19:28:49
A-7777760  Source1         2  2019-08-23 19:00:21  2019-08-23 19:29:42
A-7777761  Source1         2  2019-08-23 18:52:06  2019-08-23 19:21:31

           Start_Lat   Start_Lng   End_Lat    End_Lng  Distance(mi)  \
ID
A-1        39.865147  -84.058723       NaN        NaN         0.010
A-2        39.928059  -82.831184       NaN        NaN         0.010
A-3        39.063148  -84.032608       NaN        NaN         0.010
A-4        39.747753  -84.205582       NaN        NaN         0.010
A-5        39.627781  -84.188354       NaN        NaN         0.010
...              ...         ...       ...        ...           ...
A-7777757  34.002480 -117.379360  33.99888 -117.37094         0.543
A-7777758  32.766960 -117.148060  32.76555 -117.15363         0.338
A-7777759  33.775450 -117.847790  33.77740 -117.85727         0.561
A-7777760  33.992460 -118.403020  33.98311 -118.39565         0.772
A-7777761  34.133930 -117.230920  34.13736 -117.23934         0.537

                                                 Description  ... Station  \
ID                                                            ...
A-1        Right lane blocked due to accident on I-70 Eas...  ...   False
A-2        Accident on Brice Rd at Tussing Rd. Expect del...  ...   False
A-3        Accident on OH-32 State Route 32 Westbound at ...  ...   False
A-4        Accident on I-75 Southbound at Exits 52 52B US...  ...   False
A-5        Accident on McEwen Rd at OH-725 Miamisburg Cen...  ...   False
...                                                      ...  ...     ...
A-7777757                           At Market St - Accident.  ...   False
A-7777758    At Camino Del Rio/Mission Center Rd - Accident.  ...   False
A-7777759  At Glassell St/Grand Ave - Accident. in the ri...  ...   False
A-7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.  ...   False
A-7777761              At Highland Ave/Arden Ave - Accident.  ...   False

            Stop Traffic_Calming Traffic_Signal Turning_Loop Sunrise_Sunset  \
ID
A-1        False           False          False        False          Night
A-2        False           False          False        False          Night
A-3        False           False           True        False          Night
A-4        False           False          False        False          Night
A-5        False           False           True        False            Day
...          ...             ...            ...          ...            ...
A-7777757  False           False          False        False            Day
A-7777758  False           False          False        False            Day
A-7777759  False           False          False        False            Day
A-7777760  False           False          False        False            Day
A-7777761  False           False          False        False            Day

          Civil_Twilight Nautical_Twilight source_severity  \
ID
A-1                Night             Night        Source23
A-2                Night             Night        Source22
A-3                Night               Day        Source22
A-4                  Day               Day        Source23
A-5                  Day               Day        Source22
...                  ...               ...             ...
A-7777757            Day               Day        Source12
A-7777758            Day               Day        Source12
A-7777759            Day               Day        Source12
A-7777760            Day               Day        Source12
A-7777761            Day               Day        Source12

           Astronomical_Twilight
ID
A-1                        Night
A-2                          Day
A-3                          Day
A-4                          Day
A-5                          Day
...                          ...
A-7777757                    Day
A-7777758                    Day
A-7777759                    Day
A-7777760                    Day
A-7777761                    Day

[7728394 rows x 46 columns]

In [10]:
#delete column severity_source
df_accidents = df_accidents.drop('source_severity', axis=1)
print(df_accidents)

            Source  Severity           Start_Time             End_Time  \
ID
A-1        Source2         3  2016-02-08 05:46:00  2016-02-08 11:00:00
A-2        Source2         2  2016-02-08 06:07:59  2016-02-08 06:37:59
A-3        Source2         2  2016-02-08 06:49:27  2016-02-08 07:19:27
A-4        Source2         3  2016-02-08 07:23:34  2016-02-08 07:53:34
A-5        Source2         2  2016-02-08 07:39:07  2016-02-08 08:09:07
...            ...       ...                  ...                  ...
A-7777757  Source1         2  2019-08-23 18:03:25  2019-08-23 18:32:01
A-7777758  Source1         2  2019-08-23 19:11:30  2019-08-23 19:38:23
A-7777759  Source1         2  2019-08-23 19:00:21  2019-08-23 19:28:49
A-7777760  Source1         2  2019-08-23 19:00:21  2019-08-23 19:29:42
A-7777761  Source1         2  2019-08-23 18:52:06  2019-08-23 19:21:31

           Start_Lat   Start_Lng   End_Lat    End_Lng  Distance(mi)  \
ID
A-1        39.865147  -84.058723       NaN        NaN         0.010
A-2        39.928059  -82.831184       NaN        NaN         0.010
A-3        39.063148  -84.032608       NaN        NaN         0.010
A-4        39.747753  -84.205582       NaN        NaN         0.010
A-5        39.627781  -84.188354       NaN        NaN         0.010
...              ...         ...       ...        ...           ...
A-7777757  34.002480 -117.379360  33.99888 -117.37094         0.543
A-7777758  32.766960 -117.148060  32.76555 -117.15363         0.338
A-7777759  33.775450 -117.847790  33.77740 -117.85727         0.561
A-7777760  33.992460 -118.403020  33.98311 -118.39565         0.772
A-7777761  34.133930 -117.230920  34.13736 -117.23934         0.537

                                                 Description  ... Roundabout  \
ID                                                            ...
A-1        Right lane blocked due to accident on I-70 Eas...  ...      False
A-2        Accident on Brice Rd at Tussing Rd. Expect del...  ...      False
A-3        Accident on OH-32 State Route 32 Westbound at ...  ...      False
A-4        Accident on I-75 Southbound at Exits 52 52B US...  ...      False
A-5        Accident on McEwen Rd at OH-725 Miamisburg Cen...  ...      False
...                                                      ...  ...        ...
A-7777757                           At Market St - Accident.  ...      False
A-7777758    At Camino Del Rio/Mission Center Rd - Accident.  ...      False
A-7777759  At Glassell St/Grand Ave - Accident. in the ri...  ...      False
A-7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.  ...      False
A-7777761              At Highland Ave/Arden Ave - Accident.  ...      False

          Station   Stop Traffic_Calming Traffic_Signal Turning_Loop  \
ID
A-1         False  False           False          False        False
A-2         False  False           False          False        False
A-3         False  False           False           True        False
A-4         False  False           False          False        False
A-5         False  False           False           True        False
...           ...    ...             ...            ...          ...
A-7777757   False  False           False          False        False
A-7777758   False  False           False          False        False
A-7777759   False  False           False          False        False
A-7777760   False  False           False          False        False
A-7777761   False  False           False          False        False

          Sunrise_Sunset Civil_Twilight Nautical_Twilight  \
ID
A-1                Night          Night             Night
A-2                Night          Night             Night
A-3                Night          Night               Day
A-4                Night            Day               Day
A-5                  Day            Day               Day
...                  ...            ...               ...
A-7777757            Day            Day               Day
A-7777758            Day            Day               Day
A-7777759            Day            Day               Day
A-7777760            Day            Day               Day
A-7777761            Day            Day               Day

           Astronomical_Twilight
ID
A-1                        Night
A-2                          Day
A-3                          Day
A-4                          Day
A-5                          Day
...                          ...
A-7777757                    Day
A-7777758                    Day
A-7777759                    Day
A-7777760                    Day
A-7777761                    Day

[7728394 rows x 45 columns]

In [11]:
#use str-Accesor --> replace ID (A-1 --> 1)
df_accidents.index = df_accidents.index.str.replace('A-','')
print(df_accidents)

          Source  Severity           Start_Time             End_Time  \
ID
1        Source2         3  2016-02-08 05:46:00  2016-02-08 11:00:00
2        Source2         2  2016-02-08 06:07:59  2016-02-08 06:37:59
3        Source2         2  2016-02-08 06:49:27  2016-02-08 07:19:27
4        Source2         3  2016-02-08 07:23:34  2016-02-08 07:53:34
5        Source2         2  2016-02-08 07:39:07  2016-02-08 08:09:07
...          ...       ...                  ...                  ...
7777757  Source1         2  2019-08-23 18:03:25  2019-08-23 18:32:01
7777758  Source1         2  2019-08-23 19:11:30  2019-08-23 19:38:23
7777759  Source1         2  2019-08-23 19:00:21  2019-08-23 19:28:49
7777760  Source1         2  2019-08-23 19:00:21  2019-08-23 19:29:42
7777761  Source1         2  2019-08-23 18:52:06  2019-08-23 19:21:31

         Start_Lat   Start_Lng   End_Lat    End_Lng  Distance(mi)  \
ID
1        39.865147  -84.058723       NaN        NaN         0.010
2        39.928059  -82.831184       NaN        NaN         0.010
3        39.063148  -84.032608       NaN        NaN         0.010
4        39.747753  -84.205582       NaN        NaN         0.010
5        39.627781  -84.188354       NaN        NaN         0.010
...            ...         ...       ...        ...           ...
7777757  34.002480 -117.379360  33.99888 -117.37094         0.543
7777758  32.766960 -117.148060  32.76555 -117.15363         0.338
7777759  33.775450 -117.847790  33.77740 -117.85727         0.561
7777760  33.992460 -118.403020  33.98311 -118.39565         0.772
7777761  34.133930 -117.230920  34.13736 -117.23934         0.537

                                               Description  ... Roundabout  \
ID                                                          ...
1        Right lane blocked due to accident on I-70 Eas...  ...      False
2        Accident on Brice Rd at Tussing Rd. Expect del...  ...      False
3        Accident on OH-32 State Route 32 Westbound at ...  ...      False
4        Accident on I-75 Southbound at Exits 52 52B US...  ...      False
5        Accident on McEwen Rd at OH-725 Miamisburg Cen...  ...      False
...                                                    ...  ...        ...
7777757                           At Market St - Accident.  ...      False
7777758    At Camino Del Rio/Mission Center Rd - Accident.  ...      False
7777759  At Glassell St/Grand Ave - Accident. in the ri...  ...      False
7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.  ...      False
7777761              At Highland Ave/Arden Ave - Accident.  ...      False

        Station   Stop Traffic_Calming Traffic_Signal Turning_Loop  \
ID
1         False  False           False          False        False
2         False  False           False          False        False
3         False  False           False           True        False
4         False  False           False          False        False
5         False  False           False           True        False
...         ...    ...             ...            ...          ...
7777757   False  False           False          False        False
7777758   False  False           False          False        False
7777759   False  False           False          False        False
7777760   False  False           False          False        False
7777761   False  False           False          False        False

        Sunrise_Sunset Civil_Twilight Nautical_Twilight  Astronomical_Twilight
ID
1                Night          Night             Night                  Night
2                Night          Night             Night                    Day
3                Night          Night               Day                    Day
4                Night            Day               Day                    Day
5                  Day            Day               Day                    Day
...                ...            ...               ...                    ...
7777757            Day            Day               Day                    Day
7777758            Day            Day               Day                    Day
7777759            Day            Day               Day                    Day
7777760            Day            Day               Day                    Day
7777761            Day            Day               Day                    Day

[7728394 rows x 45 columns]

In [12]:
df_accidents.to_csv('data/edited_file.csv')