In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
accidents_df = pd.read_csv('data/edited_file.csv', index_col='ID')

In [7]:
pd.set_option('display.max_columns', None)
accidents.head()

,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,Right lane blocked due to accident on I-70 Eas...,I-70 E,Dayton,Montgomery,OH,45424,US,US/Eastern,KFFO,2016-02-08 05:58:00,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,Reynoldsburg,Franklin,OH,43068-3402,US,US/Eastern,KCMH,2016-02-08 05:51:00,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day
3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,OH,45176,US,US/Eastern,KI69,2016-02-08 06:56:00,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,OH,45417,US,US/Eastern,KDAY,2016-02-08 07:38:00,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,OH,45459,US,US/Eastern,KMGY,2016-02-08 07:53:00,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day

In [7]:
#calculate new column
accidents_df['country_state'] = accidents_df['State'].astype(str) + accidents_df['Country'].astype(str)
print(accidents_df['country_state'])

ID
1          OHUS
2          OHUS
3          OHUS
4          OHUS
5          OHUS
           ...
7777757    CAUS
7777758    CAUS
7777759    CAUS
7777760    CAUS
7777761    CAUS
Name: country_state, Length: 7728394, dtype: object

In [10]:
accidents_df

,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,country_state
ID,,,,,,,,,,,,,,,,,,,,,
1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,Right lane blocked due to accident on I-70 Eas...,...,False,False,False,False,False,Night,Night,Night,Night,OHUS
2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,Accident on Brice Rd at Tussing Rd. Expect del...,...,False,False,False,False,False,Night,Night,Night,Day,OHUS
3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,Accident on OH-32 State Route 32 Westbound at ...,...,False,False,False,True,False,Night,Night,Day,Day,OHUS
4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,Accident on I-75 Southbound at Exits 52 52B US...,...,False,False,False,False,False,Night,Day,Day,Day,OHUS
5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,...,False,False,False,True,False,Day,Day,Day,Day,OHUS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7777757,Source1,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,0.543,At Market St - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,CAUS
7777758,Source1,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,CAUS
7777759,Source1,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,Day,Day,Day,Day,CAUS
7777760,Source1,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,CAUS
7777761,Source1,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,Day,Day,Day,Day,CAUS

In [8]:
merged_df = pd.concat([accidents_df, accidents_df['country_state']], axis=1)
merged_df

,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,country_state,country_state
ID,,,,,,,,,,,,,,,,,,,,,
1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,Right lane blocked due to accident on I-70 Eas...,...,False,False,False,False,Night,Night,Night,Night,OHUS,OHUS
2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,Accident on Brice Rd at Tussing Rd. Expect del...,...,False,False,False,False,Night,Night,Night,Day,OHUS,OHUS
3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,Accident on OH-32 State Route 32 Westbound at ...,...,False,False,True,False,Night,Night,Day,Day,OHUS,OHUS
4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,Accident on I-75 Southbound at Exits 52 52B US...,...,False,False,False,False,Night,Day,Day,Day,OHUS,OHUS
5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,...,False,False,True,False,Day,Day,Day,Day,OHUS,OHUS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7777757,Source1,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,0.543,At Market St - Accident.,...,False,False,False,False,Day,Day,Day,Day,CAUS,CAUS
7777758,Source1,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,Day,Day,Day,Day,CAUS,CAUS
7777759,Source1,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,Day,Day,Day,Day,CAUS,CAUS
7777760,Source1,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,Day,Day,Day,Day,CAUS,CAUS
7777761,Source1,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,Day,Day,Day,Day,CAUS,CAUS

In [12]:
pivot_table = merged_df.pivot_table 
pivot_table

<bound method DataFrame.pivot_table of           Source  Severity           Start_Time             End_Time  \
ID
1        Source2         3  2016-02-08 05:46:00  2016-02-08 11:00:00
2        Source2         2  2016-02-08 06:07:59  2016-02-08 06:37:59
3        Source2         2  2016-02-08 06:49:27  2016-02-08 07:19:27
4        Source2         3  2016-02-08 07:23:34  2016-02-08 07:53:34
5        Source2         2  2016-02-08 07:39:07  2016-02-08 08:09:07
...          ...       ...                  ...                  ...
7777757  Source1         2  2019-08-23 18:03:25  2019-08-23 18:32:01
7777758  Source1         2  2019-08-23 19:11:30  2019-08-23 19:38:23
7777759  Source1         2  2019-08-23 19:00:21  2019-08-23 19:28:49
7777760  Source1         2  2019-08-23 19:00:21  2019-08-23 19:29:42
7777761  Source1         2  2019-08-23 18:52:06  2019-08-23 19:21:31

         Start_Lat   Start_Lng   End_Lat    End_Lng  Distance(mi)  \
ID
1        39.865147  -84.058723       NaN        NaN         0.010
2        39.928059  -82.831184       NaN        NaN         0.010
3        39.063148  -84.032608       NaN        NaN         0.010
4        39.747753  -84.205582       NaN        NaN         0.010
5        39.627781  -84.188354       NaN        NaN         0.010
...            ...         ...       ...        ...           ...
7777757  34.002480 -117.379360  33.99888 -117.37094         0.543
7777758  32.766960 -117.148060  32.76555 -117.15363         0.338
7777759  33.775450 -117.847790  33.77740 -117.85727         0.561
7777760  33.992460 -118.403020  33.98311 -118.39565         0.772
7777761  34.133930 -117.230920  34.13736 -117.23934         0.537

                                               Description  ...   Stop  \
ID                                                          ...
1        Right lane blocked due to accident on I-70 Eas...  ...  False
2        Accident on Brice Rd at Tussing Rd. Expect del...  ...  False
3        Accident on OH-32 State Route 32 Westbound at ...  ...  False
4        Accident on I-75 Southbound at Exits 52 52B US...  ...  False
5        Accident on McEwen Rd at OH-725 Miamisburg Cen...  ...  False
...                                                    ...  ...    ...
7777757                           At Market St - Accident.  ...  False
7777758    At Camino Del Rio/Mission Center Rd - Accident.  ...  False
7777759  At Glassell St/Grand Ave - Accident. in the ri...  ...  False
7777760     At CA-90/Marina Fwy/Jefferson Blvd - Accident.  ...  False
7777761              At Highland Ave/Arden Ave - Accident.  ...  False

        Traffic_Calming Traffic_Signal Turning_Loop Sunrise_Sunset  \
ID
1                 False          False        False          Night
2                 False          False        False          Night
3                 False           True        False          Night
4                 False          False        False          Night
5                 False           True        False            Day
...                 ...            ...          ...            ...
7777757           False          False        False            Day
7777758           False          False        False            Day
7777759           False          False        False            Day
7777760           False          False        False            Day
7777761           False          False        False            Day

        Civil_Twilight Nautical_Twilight Astronomical_Twilight  country_state  \
ID
1                Night             Night                 Night           OHUS
2                Night             Night                   Day           OHUS
3                Night               Day                   Day           OHUS
4                  Day               Day                   Day           OHUS
5                  Day               Day                   Day           OHUS
...                ...               ...                   ...            ...
7777757            Day               Day                   Day           CAUS
7777758            Day               Day                   Day           CAUS
7777759            Day               Day                   Day           CAUS
7777760            Day               Day                   Day           CAUS
7777761            Day               Day                   Day           CAUS

         country_state
ID
1                 OHUS
2                 OHUS
3                 OHUS
4                 OHUS
5                 OHUS
...                ...
7777757           CAUS
7777758           CAUS
7777759           CAUS
7777760           CAUS
7777761           CAUS

[7728394 rows x 47 columns]>